import { AdviserBuilder } from "@/lib/builders/adviser";
import { Adviser } from "@prisma/client";

import AdviserCard from "./components/AdviserCard";

export async function getProps(): Promise<any> {
  const adviser1 = new AdviserBuilder("John")
    .setProfileImage("https://cdn-icons-png.flaticon.com/512/3135/3135715.png")
    .build();
  const adviser2 = new AdviserBuilder("Jim")
    .setProfileImage("https://cdn-icons-png.flaticon.com/512/3135/3135715.png")
    .build();
  const adviser3 = new AdviserBuilder("Juliette")
    .setProfileImage("https://cdn-icons-png.flaticon.com/512/3135/3135715.png")
    .build();

  const advisers: Adviser[] = await [adviser1, adviser2, adviser3];

  return advisers;
}

export const metadata = {
  title: "Advisor list",
  description: "Generated by create next app",
};

export default async function page() {
  const adviserData = await getProps();

  const advisers = Array.isArray(adviserData) ? adviserData : [];

  return (
    <div>
      {advisers.map((adviser: Adviser) => (
        <AdviserCard key={adviser.id} adviser={adviser} />
      ))}
    </div>
  );
}
