import AdviserCard from "./components/AdviserCard";
import { fetchAdvisers } from "@/lib/api/fetchAdvisers";
import { AdviserIncomingDataShallow } from "@/types";

export const metadata = {
  title: "Advisor list",
  description: "Generated by create next app",
};

const getData = async () => fetchAdvisers();

export default async function page() {
  const data = await getData();

  if (typeof data === "string") {
    return <div>{data}</div>;
  }

  if (!data.length) {
    return <div>No advisers to display!</div>;
  }

  return (
    <div>
      {data.map((adviser: AdviserIncomingDataShallow) => (
        <AdviserCard key={adviser.id} adviser={adviser} />
      ))}
    </div>
  );
}
