import Navbar from "../components/Navbar";
import "../styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Advisor portal</title>
        <link
          rel="icon"
          type="image/x-icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFm1d6OTmegYML-GS9nEHgb2zQGSkV3CPdqw&usqp=CAU"
        />
      </head>
      <body className={inter.className}>
        {" "}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
